<a class="logo" href="<?php echo R ?>">Clarify</a>
<?php
$projects = array();
if (is_array($_SESSION['user']['permissions']['project']) && sizeof($_SESSION['user']['permissions']['project']) > 0) {
    $projects = $db->data('SELECT id, creator, name, slug, screen_count FROM project WHERE id IN (' . implode(',', array_keys($_SESSION['user']['permissions']['project'])) . ') ORDER BY name ASC');
}
?>
<h3>Projects<a class="btn-add-project" href="javascript:;">+ Create</a></h3>
<div class="add-project">
    <input class="project-name" type="text" placeholder="Project Name" />
    <input class="add-project-submit" type="button" value="Create Project" />
</div>
<?php if (sizeof($projects) == 0) { ?>
<div class="notice">You don't have any projects yet.</div>
<?php } ?>
<ul>
    <?php foreach ($projects as $p) { ?>
    <?php 
    //$notifications = $p['id'] == 5 ? '<span class="notifications">5</span>' : ''; 
    ?>
    <li <?php echo $p['id'] == $project_id ? 'class="active"': '' ?>>
        <a href="<?php echo R ?>project/<?php echo $p['creator'] ?>/<?php echo $p['slug'] ?>/"><?php echo $p['name'] ?> <span class="count"><?php echo $p['screen_count'] ?></span><?php echo $notifications ?></a>
    </li>
    <?php } ?>
</ul>
<!-- Project Settings -->
<?php if ($project_id > 0) { ?>
<h3><?php echo $project['name'] ?></h3>
<ul>
    <li><a href="<?php echo R ?>guide/<?php echo $project_id ?>">Generate Styleguide</a></li>
</ul>

<?php
$modules = $db->data("SELECT id, name FROM project_module WHERE project = '" . $project_id . "' ORDER BY name ASC");
?>
<h3>Module Library<?php if (sizeof($modules) > 0) { ?><a href="javascript:;" class="btn-export-terrific">&#8677; Terrific</a><?php } ?></h3>
<div class="modules">
    <?php foreach ($modules as $module) { ?>
    <a href="javascript:;" data-module="<?php echo $module['name'] ?>" data-terrific="terrific:generate:module <?php echo $module['name'] ?>"></a>
    <?php } ?>
</div>
<div class="notice">You have <?php echo sizeof($modules) ?> modules in your library.</div>
<?php if (has_permission($project_id, 'ADMIN')) { ?>
<?php
$collaborators = $db->data('SELECT id, email FROM project_collaborator WHERE creator = ' . userid() . ' AND project = ' . $project_id . ' ORDER BY email ASC');
?>
<h3>
    Collaborators
    <a class="btn-add-collaborator" href="javascript:;">+ Add</a>
</h3>
<div class="add-collaborator">
    <input class="collaborator-email" data-project-id="<?php echo $project_id ?>" type="text" placeholder="E-Mail" />
    <input class="add-collaborator-submit" type="button" value="Add User" />
</div>
<?php if (sizeof($collaborators) == 0) { ?>
    <div class="notice">You don't have any collaborators yet.</div>
<?php } ?>
<ul class="collaborators">
    <?php foreach ($collaborators as $c) { ?>
    <li>
        <div class="edit-collaborator" data-id="<?php echo $c['id'] ?>" href="#">
            <img src="<?php echo gravatar($c['email'], 24) ?>" width="24" height="24" />
            <span><?php echo $c['email'] ?></span>
            <a href="javascript:;" class="remove">&times;</a>
        </div>
    </li>
    <?php } ?>
</ul>
<?php } ?>
<?php } ?>