<?php
if ($project_id > 0) {
    permission($project_id, 'VIEW');
    $screens = $db->data('
        SELECT 
            id, 
            project, 
            title, 
            width, 
            height, 
            ext, 
            created, 
            count_comment, 
            count_measure, 
            count_color, 
            count_font, 
            count_module
        FROM screen 
        WHERE project = ' . $project_id . ' 
        ORDER BY title ASC
    ');
    $project = $db->single("SELECT name FROM project WHERE id = '" . $project_id . "'");
}

// load color library for this project
$colors = $db->data("
    SELECT id, hex, name, name_css 
    FROM project_color 
    WHERE project = '" . $project_id . "' 
    ORDER BY hue ASC
");

?>
<div class="head">
    <h2><?php echo $project_id > 0 ? $project['name'] : 'Create or Choose a Project' ?></h2>
    <?php if ($project_id > 0) { ?>
    <div class="actions">
        <?php if (has_permission($project_id, 'ADMIN')) { ?>
        <a href="javascript:;" class="btn-rename-project" data-project="<?php echo $project_id ?>" data-name="<?php echo $project['name'] ?>">Rename</a>
        <a href="javascript:;" class="btn-delete-project" data-project="<?php echo $project_id ?>">Delete</a>
        <?php } ?>
    </div>
    <?php } ?>
    <div class="usermeta">
        <div class="info">
            <p class="username"><?php echo user('name') ?></p>
            <a href="<?php echo R ?>auth/?wipe=1">Logout</a>
        </div>
        <div class="avatar">
            <img src="<?php echo $_SESSION['user']['twitter']->profile_image_url ?>" width="48" height="48" />
        </div>
    </div>
</div>
<?php if ($project_id > 0) { ?>
<div class="colors">
    <?php foreach ($colors as $color) { ?>
    <a href="javascript:;" rel="tooltip" title="<?php echo $color['name'] ?> – #<?php echo $color['hex'] ?>" data-less="@<?php echo $color['name_css'] ?>: #<?php echo $color['hex'] ?>;" data-sass="$<?php echo $color['name_css'] ?>: #<?php echo $color['hex'] ?>;" data-hex="#<?php echo $color['hex'] ?>" class="color color-<?php echo $color['id'] ?>" style="background: #<?php echo $color['hex'] ?>"></a>
    <?php } ?>
    <a href="javascript:;" class="export btn-export-css">.LESS</a>
    <a href="javascript:;" class="export btn-export-sass">.SASS</a>
    <a href="<?php echo R ?>api/color/export/<?php echo $project_id ?>/aco" class="export btn-export-aco">.ACO</a>
</div>
<ul>
    <?php if (has_permission($project_id, 'EDIT')) { ?>
    <li class="create">
        <a class="placeholder" href="javascript:;"><div></div></a>
        <p class="title-placeholder"><a href="#"><span>Click to upload screens</span></a></p>
        <p class="meta">JPG or PNG (max. 10 MB)</p>
    </li>
    <?php } ?>
    <?php foreach ($screens as $screen) { ?>
    <li class="screen screen-<?php echo $screen['id'] ?>">
        <a class="image" href="<?php echo R ?>screen/<?php echo $screen['id'] ?>">
            <img src="/upload/screens/<?php echo $project_id ?>/thumbnails/<?php echo md5($screen['id'] .config('security.general.hash')) ?>.<?php echo $screen['ext'] ?>" width="200" alt="" />
            <div class="info">
                <i class="icon-white icon-comment"></i> <span<?php echo $screen['count_comment'] == 0 ? ' class="zero"' : '' ?>><?php echo $screen['count_comment'] ?></span>
                <i class="icon-white icon-resize-vertical"></i> <span<?php echo $screen['count_measure'] == 0 ? ' class="zero"' : '' ?>><?php echo $screen['count_measure'] ?></span>
                <i class="icon-white icon-tint"></i> <span<?php echo $screen['count_color'] == 0 ? ' class="zero"' : '' ?>><?php echo $screen['count_color'] ?></span>
                <i class="icon-white icon-font"></i> <span<?php echo $screen['count_font'] == 0 ? ' class="zero"' : '' ?>><?php echo $screen['count_font'] ?></span>
                <i class="icon-white icon-th-large"></i> <span<?php echo $screen['count_module'] == 0 ? ' class="zero"' : '' ?>><?php echo $screen['count_module'] ?></span>
            </div>
        </a>
        <p class="title"><a href="javascript:;" data-screen="<?php echo $screen['id'] ?>" data-title="<?php echo $screen['title'] ?>"><span><?php echo htmlspecialchars(truncate($screen['title'],30,'...')) ?></span></a></p>
        <p class="meta">
            <span class="size"><?php echo $screen['width'] ?> &times; <?php echo $screen['height'] ?></span>
            <?php if (has_permission($screen['project'], 'EDIT')) { ?>
            <a class="delete" data-screen="<?php echo $screen['id'] ?>" href="javascript:;">×</a>
            <?php } ?>
        </p>
    </li>
    <?php } ?>
</ul>
<input class="fileupload" type="file" name="files[]" multiple>
<?php } else { ?>
<a class="btn-create-project" href="#">Create Project</a>
<?php } ?>