<div class="scroller">
<?php foreach ($modules as $module) { ?>
<a href="javascript:;" rel="tooltip" title="<?php echo $module['name'] ?>" class="module module-<?php echo $module['id'] ?>" data-id="<?php echo $module['id'] ?>" data-name="<?php echo $module['name'] ?>">
    <div class="rename"><span class="desc"><?php echo $module['name'] ?></span> <i class="icon icon-white icon-pencil"></i></div>
    <img src="<?php echo R .'upload/modules/' . $screen['project'] .'/'. md5($module['id'] . config('security.general.hash')) ?>.png" />
</a>
<?php } ?>
</div>